name: E_Soor
description: Online Bookstore and socialmedia

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    #state managment
    provider: ^4.0.5
    #packages
    splashscreen:
        git:
            url: git://github.com/OmarYehiaDev/SplashScreenFlutterPackage
    auto_size_text: ^2.1.0
    flutter_icons: ^1.1.0
    image_picker: ^0.6.7
    flutter_credit_card: ^0.1.3
    carousel_slider: ^2.1.0
    material_design_icons_flutter: ^4.0.5145
    flutter_login: ^1.0.14
    sliding_up_panel: ^1.0.0
    response: ^0.0.1+4
    flutter_rating_bar: ^3.0.1+1
    flutter_reaction_button:
        git:
            url: git://github.com/OmarYehiaDev/flutter-reaction-button
    audioplayers: ^0.15.0
    bottomreveal: ^1.0.0
    timeago:
    circular_profile_avatar:
    cupertino_icons: ^0.1.2
    flushbar: 1.10.2
    cached_network_image:
    login:
    velocity_x: ^0.4.0
    settings_ui:
        git:
            url: git://github.com/OmarYehiaDev/flutter-settings-ui
    #local database
    shared_preferences: ^0.5.7
    #backend
    url_launcher: 5.4.5
    flutter_facebook_login: ^3.0.0
    google_sign_in:
    firebase_auth:
    firebase_messaging:
    http:
    cloud_firestore:
    firebase_remote_config: ^0.3.0+3
    firebase_storage: ^3.1.5

dev_dependencies:
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/json/
        - assets/sounds/
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
